// ============================================
// PR & MARKETING MOCK DATA
// ============================================

// Media Types
export type MediaType = 'TV' | 'PRINT' | 'ONLINE' | 'PODCAST' | 'RADIO' | 'SOCIAL'
export type MentionStatus = 'ACTIVE' | 'ARCHIVED' | 'FLAGGED'
export type Sentiment = 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE'
export type ImportSource = 'MANUAL' | 'CSV_IMPORT' | 'CISION' | 'MELTWATER'

// Award Types
export type AwardStatus = 'APPLIED' | 'NOMINATED' | 'SEMIFINALIST' | 'FINALIST' | 'WON' | 'NOT_SELECTED'
export type RecipientType = 'RESTAURANT' | 'CHEF' | 'HOSPITALITY_GROUP' | 'SOMMELIER' | 'BARTENDER' | 'DISH' | 'BEVERAGE_PROGRAM'

// Media Type Config
export const mediaTypeConfig: Record<MediaType, { name: string; color: string; bgColor: string; icon: string }> = {
  TV: { name: 'TV', color: '#7C3AED', bgColor: '#F5F3FF', icon: 'tv' },
  PRINT: { name: 'Print', color: '#0891B2', bgColor: '#ECFEFF', icon: 'newspaper' },
  ONLINE: { name: 'Online', color: '#059669', bgColor: '#ECFDF5', icon: 'globe' },
  PODCAST: { name: 'Podcast', color: '#DC2626', bgColor: '#FEF2F2', icon: 'mic' },
  RADIO: { name: 'Radio', color: '#D97706', bgColor: '#FFFBEB', icon: 'radio' },
  SOCIAL: { name: 'Social', color: '#2563EB', bgColor: '#EFF6FF', icon: 'share-2' },
}

// Award Status Config
export const awardStatusConfig: Record<AwardStatus, { name: string; color: string; bgColor: string; icon: string }> = {
  APPLIED: { name: 'Applied', color: '#6B7280', bgColor: '#F3F4F6', icon: 'file-text' },
  NOMINATED: { name: 'Nominated', color: '#3B82F6', bgColor: '#EFF6FF', icon: 'award' },
  SEMIFINALIST: { name: 'Semifinalist', color: '#8B5CF6', bgColor: '#F5F3FF', icon: 'medal' },
  FINALIST: { name: 'Finalist', color: '#F59E0B', bgColor: '#FFFBEB', icon: 'trophy' },
  WON: { name: 'Winner', color: '#10B981', bgColor: '#ECFDF5', icon: 'crown' },
  NOT_SELECTED: { name: 'Not Selected', color: '#9CA3AF', bgColor: '#F9FAFB', icon: 'x-circle' },
}

// Media Mention Interface
export interface MediaMention {
  id: string
  headline: string
  outlet: string
  outletType: MediaType
  publishedAt: string
  uvm: number | null
  ave: number | null
  totalEngagement: number | null
  link: string | null
  imageUrl: string | null
  description: string | null
  journalistName: string | null
  journalistEmail: string | null
  sentiment: Sentiment
  topics: string[]
  isHighlight: boolean
  internalNotes: string | null
  importSource: ImportSource
}

// Award Interface
export interface Award {
  id: string
  name: string
  organization: string
  category: string | null
  status: AwardStatus
  year: number
  nominatedAt: string | null
  awardedAt: string | null
  description: string | null
  link: string | null
  recipientType: RecipientType
  recipientName: string | null
  isFeatured: boolean
}

// PR Summary Stats
export const mockPRStats = {
  totalMentions: 18,
  totalReach: 12450000, // UVM
  totalAVE: 847500,
  totalEngagement: 34200,
  mentionsChange: 3,
  reachChange: 15.2,
  aveChange: 22.8,
  engagementChange: 18.5,
}

// Mentions Over Time (12 months)
export const mockMentionsOverTime = [
  { date: '2024-02', value: 8 },
  { date: '2024-03', value: 12 },
  { date: '2024-04', value: 9 },
  { date: '2024-05', value: 15 },
  { date: '2024-06', value: 11 },
  { date: '2024-07', value: 14 },
  { date: '2024-08', value: 10 },
  { date: '2024-09', value: 16 },
  { date: '2024-10', value: 13 },
  { date: '2024-11', value: 18 },
  { date: '2024-12', value: 15 },
  { date: '2025-01', value: 18 },
]

// Reach by Media Type (for donut chart)
export const mockReachByType = [
  { name: 'TV', value: 5200000, color: '#7C3AED' },
  { name: 'Print', value: 2800000, color: '#0891B2' },
  { name: 'Online', value: 3450000, color: '#059669' },
  { name: 'Podcast', value: 1000000, color: '#DC2626' },
]

// AVE Trend (12 months)
export const mockAVETrend = [
  { date: '2024-02', value: 42000 },
  { date: '2024-03', value: 68000 },
  { date: '2024-04', value: 51000 },
  { date: '2024-05', value: 89000 },
  { date: '2024-06', value: 62000 },
  { date: '2024-07', value: 78000 },
  { date: '2024-08', value: 55000 },
  { date: '2024-09', value: 95000 },
  { date: '2024-10', value: 71000 },
  { date: '2024-11', value: 112000 },
  { date: '2024-12', value: 82000 },
  { date: '2025-01', value: 125000 },
]

// Mock Media Mentions (18 items)
export const mockMediaMentions: MediaMention[] = [
  {
    id: 'mention-1',
    headline: 'Chef Michael Solomonov to Headline San Antonio Food & Wine Festival',
    outlet: 'KSAT-TV',
    outletType: 'TV',
    publishedAt: '2025-01-22',
    uvm: 1850000,
    ave: 45000,
    totalEngagement: 3200,
    link: 'https://www.ksat.com/entertainment/food/2025/01/22/chef-solomonov-headlines-festival',
    imageUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=120&h=80&fit=crop',
    description: 'Celebrity chef Michael Solomonov announced as keynote speaker for the annual San Antonio Food & Wine Festival. Restaurant Gwendolyn to host exclusive dinner event.',
    journalistName: 'Sarah Mitchell',
    journalistEmail: 's.mitchell@ksat.com',
    sentiment: 'POSITIVE',
    topics: ['event', 'chef feature', 'food festival'],
    isHighlight: true,
    internalNotes: 'Great coverage - led the 6pm news segment',
    importSource: 'MANUAL',
  },
  {
    id: 'mention-2',
    headline: 'The 25 Best Restaurants in Texas for 2025',
    outlet: 'Texas Monthly',
    outletType: 'PRINT',
    publishedAt: '2025-01-18',
    uvm: 2100000,
    ave: 85000,
    totalEngagement: 8500,
    link: 'https://www.texasmonthly.com/food/25-best-restaurants-texas-2025',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=120&h=80&fit=crop',
    description: 'Restaurant Gwendolyn ranked #8 on Texas Monthly\'s prestigious annual list, praised for its commitment to farm-to-table dining and innovative seasonal menus.',
    journalistName: 'Patricia Sharpe',
    journalistEmail: 'psharpe@texasmonthly.com',
    sentiment: 'POSITIVE',
    topics: ['award', 'ranking', 'review'],
    isHighlight: true,
    internalNotes: 'Major annual recognition - use in marketing materials',
    importSource: 'MANUAL',
  },
  {
    id: 'mention-3',
    headline: 'San Antonio\'s Farm-to-Table Revolution',
    outlet: 'San Antonio Express-News',
    outletType: 'PRINT',
    publishedAt: '2025-01-15',
    uvm: 890000,
    ave: 32000,
    totalEngagement: 1800,
    link: 'https://www.expressnews.com/food/article/farm-to-table-revolution-2025',
    imageUrl: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=120&h=80&fit=crop',
    description: 'Feature article exploring the local farm-to-table movement, with Restaurant Gwendolyn highlighted as a pioneer in sustainable dining.',
    journalistName: 'Mike Sutter',
    journalistEmail: 'msutter@express-news.net',
    sentiment: 'POSITIVE',
    topics: ['sustainability', 'farm-to-table', 'feature'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'MANUAL',
  },
  {
    id: 'mention-4',
    headline: 'Dining Out: New Winter Menus Worth Trying',
    outlet: 'WOAI-TV',
    outletType: 'TV',
    publishedAt: '2025-01-12',
    uvm: 1200000,
    ave: 28000,
    totalEngagement: 2100,
    link: 'https://news4sanantonio.com/features/dining-out-winter-menus',
    imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=120&h=80&fit=crop',
    description: 'TV segment featuring Restaurant Gwendolyn\'s new winter tasting menu, including interview with Executive Chef.',
    journalistName: 'Lisa Krantz',
    journalistEmail: null,
    sentiment: 'POSITIVE',
    topics: ['menu', 'seasonal', 'chef interview'],
    isHighlight: false,
    internalNotes: 'Chef did great on camera',
    importSource: 'MANUAL',
  },
  {
    id: 'mention-5',
    headline: 'The Future of Fine Dining with Chef Marcus Thompson',
    outlet: 'Eater Podcast',
    outletType: 'PODCAST',
    publishedAt: '2025-01-10',
    uvm: 450000,
    ave: 18000,
    totalEngagement: 4200,
    link: 'https://www.eater.com/podcasts/future-fine-dining',
    imageUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=120&h=80&fit=crop',
    description: 'Hour-long podcast interview discussing sustainability, local sourcing, and the evolution of fine dining in Texas.',
    journalistName: 'Daniel Geneen',
    journalistEmail: 'daniel@eater.com',
    sentiment: 'POSITIVE',
    topics: ['podcast', 'chef interview', 'sustainability'],
    isHighlight: true,
    internalNotes: 'Share on social - great quotes throughout',
    importSource: 'MANUAL',
  },
  {
    id: 'mention-6',
    headline: 'Where to Celebrate Valentine\'s Day in San Antonio',
    outlet: 'San Antonio Magazine',
    outletType: 'PRINT',
    publishedAt: '2025-01-08',
    uvm: 320000,
    ave: 15000,
    totalEngagement: 1200,
    link: 'https://www.sanantoniomag.com/valentines-day-restaurants-2025',
    imageUrl: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=120&h=80&fit=crop',
    description: 'Restaurant Gwendolyn featured as top romantic dining destination with special Valentine\'s menu preview.',
    journalistName: 'Ashley Torres',
    journalistEmail: 'atorres@sanantoniomag.com',
    sentiment: 'POSITIVE',
    topics: ['valentines', 'romantic dining', 'special menu'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'CSV_IMPORT',
  },
  {
    id: 'mention-7',
    headline: 'Local Restaurants Embrace Zero-Waste Cooking',
    outlet: 'MySA.com',
    outletType: 'ONLINE',
    publishedAt: '2025-01-05',
    uvm: 680000,
    ave: 22000,
    totalEngagement: 3400,
    link: 'https://www.mysanantonio.com/food/zero-waste-restaurants',
    imageUrl: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=120&h=80&fit=crop',
    description: 'Article highlighting Restaurant Gwendolyn\'s zero-waste initiatives and partnership with local farms.',
    journalistName: 'Chuck Blount',
    journalistEmail: 'cblount@express-news.net',
    sentiment: 'POSITIVE',
    topics: ['sustainability', 'zero-waste', 'environment'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'MANUAL',
  },
  {
    id: 'mention-8',
    headline: 'Pearl District Dining Guide 2025',
    outlet: 'Culture Map San Antonio',
    outletType: 'ONLINE',
    publishedAt: '2024-12-28',
    uvm: 520000,
    ave: 19000,
    totalEngagement: 2800,
    link: 'https://sanantonio.culturemap.com/pearl-dining-guide-2025',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=120&h=80&fit=crop',
    description: 'Comprehensive guide to Pearl District restaurants featuring Restaurant Gwendolyn as a must-visit destination.',
    journalistName: 'Raven Santana',
    journalistEmail: 'rsantana@culturemap.com',
    sentiment: 'POSITIVE',
    topics: ['guide', 'pearl district', 'recommendation'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'CSV_IMPORT',
  },
  {
    id: 'mention-9',
    headline: 'Best New Year\'s Eve Dining Experiences',
    outlet: 'KENS-TV',
    outletType: 'TV',
    publishedAt: '2024-12-26',
    uvm: 1650000,
    ave: 38000,
    totalEngagement: 1900,
    link: 'https://www.kens5.com/article/new-years-eve-dining-2024',
    imageUrl: 'https://images.unsplash.com/photo-1482275548304-a58859dc31b7?w=120&h=80&fit=crop',
    description: 'Live segment showcasing Restaurant Gwendolyn\'s New Year\'s Eve tasting menu and champagne pairings.',
    journalistName: 'Barry Davis',
    journalistEmail: null,
    sentiment: 'POSITIVE',
    topics: ['new years', 'special event', 'wine'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'MANUAL',
  },
  {
    id: 'mention-10',
    headline: 'Texas Chefs Leading the Sustainability Movement',
    outlet: 'Food & Wine',
    outletType: 'PRINT',
    publishedAt: '2024-12-20',
    uvm: 4500000,
    ave: 125000,
    totalEngagement: 6200,
    link: 'https://www.foodandwine.com/texas-sustainable-chefs',
    imageUrl: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=120&h=80&fit=crop',
    description: 'National feature highlighting Chef Marcus Thompson among Texas leaders in sustainable fine dining.',
    journalistName: 'Kat Kinsman',
    journalistEmail: 'kat.kinsman@foodandwine.com',
    sentiment: 'POSITIVE',
    topics: ['national press', 'sustainability', 'chef feature'],
    isHighlight: true,
    internalNotes: 'MAJOR national coverage - priority for all marketing',
    importSource: 'MANUAL',
  },
  {
    id: 'mention-11',
    headline: 'Holiday Gift Guide: Restaurant Gift Cards',
    outlet: 'San Antonio Current',
    outletType: 'ONLINE',
    publishedAt: '2024-12-15',
    uvm: 280000,
    ave: 8500,
    totalEngagement: 950,
    link: 'https://www.sacurrent.com/holiday-gift-cards-2024',
    imageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=120&h=80&fit=crop',
    description: 'Restaurant Gwendolyn gift cards featured in annual holiday gift guide.',
    journalistName: 'Jessica Rodriguez',
    journalistEmail: 'jrodriguez@sacurrent.com',
    sentiment: 'POSITIVE',
    topics: ['holiday', 'gift cards', 'guide'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'CSV_IMPORT',
  },
  {
    id: 'mention-12',
    headline: 'Behind the Scenes at San Antonio\'s Top Kitchens',
    outlet: 'Bon Appétit YouTube',
    outletType: 'ONLINE',
    publishedAt: '2024-12-10',
    uvm: 2800000,
    ave: 95000,
    totalEngagement: 12500,
    link: 'https://www.youtube.com/watch?v=example123',
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=120&h=80&fit=crop',
    description: 'Video feature taking viewers behind the scenes at Restaurant Gwendolyn, showing prep work and plating.',
    journalistName: 'Brad Leone',
    journalistEmail: null,
    sentiment: 'POSITIVE',
    topics: ['video', 'behind the scenes', 'kitchen'],
    isHighlight: true,
    internalNotes: 'Over 500K views in first week - incredible exposure',
    importSource: 'MANUAL',
  },
  {
    id: 'mention-13',
    headline: 'San Antonio Sommeliers to Watch',
    outlet: 'Wine Spectator',
    outletType: 'PRINT',
    publishedAt: '2024-12-05',
    uvm: 1850000,
    ave: 72000,
    totalEngagement: 3100,
    link: 'https://www.winespectator.com/san-antonio-sommeliers',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=120&h=80&fit=crop',
    description: 'Restaurant Gwendolyn\'s sommelier featured among rising stars in Texas wine scene.',
    journalistName: 'James Molesworth',
    journalistEmail: null,
    sentiment: 'POSITIVE',
    topics: ['wine', 'sommelier', 'staff feature'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'MANUAL',
  },
  {
    id: 'mention-14',
    headline: 'The Best Tasting Menus in America',
    outlet: 'Eater National',
    outletType: 'ONLINE',
    publishedAt: '2024-11-28',
    uvm: 8500000,
    ave: 185000,
    totalEngagement: 9800,
    link: 'https://www.eater.com/best-tasting-menus-america-2024',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=120&h=80&fit=crop',
    description: 'Restaurant Gwendolyn\'s 10-course tasting menu named among 50 best in America.',
    journalistName: 'Hillary Dixler Canavan',
    journalistEmail: 'hdixler@eater.com',
    sentiment: 'POSITIVE',
    topics: ['national press', 'tasting menu', 'ranking'],
    isHighlight: true,
    internalNotes: 'Huge national recognition - update website immediately',
    importSource: 'MANUAL',
  },
  {
    id: 'mention-15',
    headline: 'Thanksgiving Special: Chef Recipes for the Home Cook',
    outlet: 'TODAY Show',
    outletType: 'TV',
    publishedAt: '2024-11-20',
    uvm: 12000000,
    ave: 280000,
    totalEngagement: 15200,
    link: 'https://www.today.com/food/thanksgiving-chef-recipes',
    imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=120&h=80&fit=crop',
    description: 'Chef Marcus Thompson shares Thanksgiving recipes on NBC\'s TODAY show morning segment.',
    journalistName: null,
    journalistEmail: null,
    sentiment: 'POSITIVE',
    topics: ['national TV', 'thanksgiving', 'recipes'],
    isHighlight: true,
    internalNotes: 'NATIONAL TV APPEARANCE - Career milestone',
    importSource: 'MANUAL',
  },
  {
    id: 'mention-16',
    headline: 'Local Restaurant Industry Rebounds Post-Pandemic',
    outlet: 'San Antonio Business Journal',
    outletType: 'PRINT',
    publishedAt: '2024-11-15',
    uvm: 420000,
    ave: 18000,
    totalEngagement: 680,
    link: 'https://www.bizjournals.com/sanantonio/restaurant-recovery',
    imageUrl: null,
    description: 'Industry analysis featuring Restaurant Gwendolyn owner discussing business recovery and growth strategies.',
    journalistName: 'W. Scott Bailey',
    journalistEmail: 'sbailey@bizjournals.com',
    sentiment: 'NEUTRAL',
    topics: ['business', 'industry', 'recovery'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'MANUAL',
  },
  {
    id: 'mention-17',
    headline: 'Wine Dinner Series Launches at Local Restaurant',
    outlet: '210 Wine & Dine Podcast',
    outletType: 'PODCAST',
    publishedAt: '2024-11-08',
    uvm: 85000,
    ave: 4500,
    totalEngagement: 1200,
    link: 'https://podcasts.apple.com/210-wine-dine',
    imageUrl: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=120&h=80&fit=crop',
    description: 'Interview discussing upcoming wine dinner series and partnership with Texas vineyards.',
    journalistName: 'Roberto Garcia',
    journalistEmail: 'roberto@210winedine.com',
    sentiment: 'POSITIVE',
    topics: ['wine', 'events', 'podcast'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'CSV_IMPORT',
  },
  {
    id: 'mention-18',
    headline: 'Where the Chefs Eat: San Antonio Edition',
    outlet: 'Thrillist',
    outletType: 'ONLINE',
    publishedAt: '2024-10-30',
    uvm: 3200000,
    ave: 68000,
    totalEngagement: 4800,
    link: 'https://www.thrillist.com/where-chefs-eat-san-antonio',
    imageUrl: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=120&h=80&fit=crop',
    description: 'Restaurant Gwendolyn mentioned by multiple local chefs as their favorite dining destination.',
    journalistName: 'Kevin Alexander',
    journalistEmail: null,
    sentiment: 'POSITIVE',
    topics: ['recommendation', 'chef endorsement', 'guide'],
    isHighlight: false,
    internalNotes: null,
    importSource: 'MANUAL',
  },
]

// Mock Awards (8 items across 2024-2026)
export const mockAwards: Award[] = [
  {
    id: 'award-1',
    name: 'Best Chef: Texas',
    organization: 'James Beard Foundation',
    category: 'Regional Chef',
    status: 'FINALIST',
    year: 2025,
    nominatedAt: '2025-01-08',
    awardedAt: null,
    description: 'Chef Marcus Thompson named as finalist for the prestigious James Beard Award for Best Chef in Texas region.',
    link: 'https://www.jamesbeard.org/awards',
    recipientType: 'CHEF',
    recipientName: 'Chef Marcus Thompson',
    isFeatured: true,
  },
  {
    id: 'award-2',
    name: 'AAA Four Diamond Award',
    organization: 'AAA',
    category: 'Fine Dining',
    status: 'WON',
    year: 2025,
    nominatedAt: null,
    awardedAt: '2025-01-02',
    description: 'Restaurant Gwendolyn awarded Four Diamond status for exceptional dining experience.',
    link: 'https://www.aaa.com/diamonds',
    recipientType: 'RESTAURANT',
    recipientName: null,
    isFeatured: true,
  },
  {
    id: 'award-3',
    name: 'Wine Spectator Award of Excellence',
    organization: 'Wine Spectator',
    category: 'Wine Program',
    status: 'WON',
    year: 2024,
    nominatedAt: null,
    awardedAt: '2024-08-15',
    description: 'Recognition for outstanding wine program and sommelier expertise.',
    link: 'https://www.winespectator.com/restaurant-awards',
    recipientType: 'BEVERAGE_PROGRAM',
    recipientName: null,
    isFeatured: false,
  },
  {
    id: 'award-4',
    name: 'Best Fine Dining Restaurant',
    organization: 'San Antonio Magazine',
    category: 'Readers\' Choice',
    status: 'WON',
    year: 2024,
    nominatedAt: '2024-06-01',
    awardedAt: '2024-09-20',
    description: 'Voted #1 Fine Dining Restaurant by San Antonio Magazine readers.',
    link: 'https://www.sanantoniomag.com/best-of',
    recipientType: 'RESTAURANT',
    recipientName: null,
    isFeatured: true,
  },
  {
    id: 'award-5',
    name: 'Rising Star Chef',
    organization: 'StarChefs',
    category: 'Emerging Talent',
    status: 'WON',
    year: 2024,
    nominatedAt: '2024-03-15',
    awardedAt: '2024-06-10',
    description: 'Sous Chef Elena Vargas recognized as Rising Star in Texas culinary scene.',
    link: 'https://www.starchefs.com/rising-stars',
    recipientType: 'CHEF',
    recipientName: 'Elena Vargas',
    isFeatured: false,
  },
  {
    id: 'award-6',
    name: 'Best New Restaurant',
    organization: 'Eater Austin/San Antonio',
    category: null,
    status: 'NOMINATED',
    year: 2024,
    nominatedAt: '2024-01-10',
    awardedAt: null,
    description: 'Nominated for Eater\'s annual best new restaurant recognition.',
    link: 'https://www.eater.com/awards',
    recipientType: 'RESTAURANT',
    recipientName: null,
    isFeatured: false,
  },
  {
    id: 'award-7',
    name: 'Sustainability Excellence Award',
    organization: 'Green Restaurant Association',
    category: 'Fine Dining',
    status: 'APPLIED',
    year: 2026,
    nominatedAt: null,
    awardedAt: null,
    description: 'Application submitted for recognition of sustainable practices and zero-waste initiatives.',
    link: 'https://www.dinegreen.com',
    recipientType: 'RESTAURANT',
    recipientName: null,
    isFeatured: false,
  },
  {
    id: 'award-8',
    name: 'OpenTable Diners\' Choice',
    organization: 'OpenTable',
    category: 'Top 100 Restaurants',
    status: 'WON',
    year: 2024,
    nominatedAt: null,
    awardedAt: '2024-12-01',
    description: 'Named among top 100 restaurants in America based on diner reviews.',
    link: 'https://www.opentable.com/lists/top-100',
    recipientType: 'RESTAURANT',
    recipientName: null,
    isFeatured: true,
  },
]

// CSV Template columns
export const csvTemplateColumns = [
  'headline',
  'outlet',
  'outletType',
  'publishedAt',
  'uvm',
  'ave',
  'totalEngagement',
  'link',
  'description',
  'journalistName',
  'journalistEmail',
  'sentiment',
  'topics',
  'isHighlight',
]

// Topic options for filtering
export const topicOptions = [
  'chef feature',
  'chef interview',
  'ranking',
  'review',
  'event',
  'menu',
  'seasonal',
  'sustainability',
  'farm-to-table',
  'zero-waste',
  'wine',
  'podcast',
  'national press',
  'national TV',
  'award',
  'guide',
  'recommendation',
  'business',
  'holiday',
]
